spring:
  devtools:
    add-properties: false
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off

# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.naming.physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    db-demo:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/demoSpringBoot
      username: postgres
      password: 123456